name: Webhook
env:
  REPO_OWNER: harshitgupta412
  REPO_NAME: temp-github-action
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [webhook]
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.16' # install the python version needed
          
      - name: install python packages # change here
        run: |
          python -m pip install --upgrade pip 
          
      - name: execute py script # run sj-gobierno.py to get the latest data
        run: python a.py ${{ github.event.client_payload.command }}
          
      - name: commit files
        uses: oleksiyrudenko/gha-git-credentials@v2.1.1
        with:
          global: true
          name: 'Harshit Gupta'
          email: 'mail4harshit1@gmail.com'
          actor: 'github action'
          token: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          git config --local user.email "mail4harshit1@gmail.com"
          git config --local user.name "Harshit Gupta"
          git add -A
          git commit -m "update data" -a 
          git push